services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mock_db
    ports:
      - "5432:5432"
    volumes:
      - ./mock_data:/mock_data  